### ISSUE TITLE
Establishing connection to api commented out

### ISSUE THREAD

**Issue by rmcwilliam** [adafruit/io-client-ruby#2]
Please see line #57 in io-client-ruby/lib/adafruit/io/client.rb 

This very important connection has been commented out. Also, it still has hashie dependency.

```
57  #connection = Faraday.new(:url => 'https://io.adafruit.com') do |c|
```

**Comment by justinh24** [comment]
I noticed this when review the code (have yet had time to test) and it look a bit suspicious to me as well.

**Comment by jwcooper** [comment]
I've pushed out a new version that fixes these two issues. Thanks!

(We'll be migrating this library to an entirely new version soon too.)
